cable_config: &cable_config
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}/5" %>
  channel_prefix: flap

production:
  <<: *cable_config

development:
  <<: *cable_config

staging:
  <<: *cable_config

test:
  adapter: async
