db_config: &db_config
  adapter:  <%= ENV['DB_ADAPTER'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  encoding: utf8

production:
  <<: *db_config

staging:
  <<: *db_config

development:
  <<: *db_config

test:
  <<: *db_config
  database: <%= "#{ENV['DB_NAME']}_test" %>
