---
# DB Config
db_adapter: <%= ENV['DB_ADAPTER'] %>
db_host:    <%= ENV['DB_HOST'] %>
db_port:    <%= ENV['DB_PORT'] %>
db_name:    <%= ENV['DB_NAME'] %>
db_user:    <%= ENV['DB_USER'] %>
db_pass:    <%= ENV['DB_PASS'] %>

# Redis
redis_host: <%= ENV['REDIS_HOST'] %>
redis_port: <%= ENV['REDIS_PORT'] %>

# Devise config
session_timeout: <%= ENV['SESSION_TIMEOUT'] %>

# App config
application_domain: <%= ENV['APPLICATION_DOMAIN'] %>

# Monitoring config
mail_on_application_error: <%= ENV['MAIL_ON_APPLICATION_ERROR'] %>
status_page_user:          <%= ENV['STATUS_PAGE_USER'] %>
status_page_pass:          <%= ENV['STATUS_PAGE_PASS'] %>

# SMTP config
smtp_host:   <%= ENV['SMTP_HOST'] %>
smtp_port:   <%= ENV['SMTP_PORT'] %>
smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
smtp_user:   <%= ENV['SMTP_USER'] %>
smtp_pass:   <%= ENV['SMTP_PASS'] %>
mail_from:   <%= ENV['MAIL_FROM'] %>
