---
# DB Config
db_adapter: <%= ENV['DB_ADAPTER'] %>
db_host:    <%= ENV['DB_HOST'] %>
db_port:    <%= ENV['DB_PORT'] %>
db_name:    <%= ENV['DB_NAME'] %>
db_user:    <%= ENV['DB_USER'] %>
db_pass:    <%= ENV['DB_PASS'] %>

# Redis
redis_host: <%= ENV['REDIS_HOST'] %>
redis_port: <%= ENV['REDIS_PORT'] %>

# Devise config
session_timeout: <%= ENV['SESSION_TIMEOUT'] %>

# App config
application_domain: <%= ENV['APPLICATION_DOMAIN'] %>
